# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/.Xil/Vivado-6676-DESKTOP-FGTB7AJ/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z010clg225-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    c:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/zynqberrydemo1.srcs/sources_1/bd/zsys/ipshared/b37e/hdl
    c:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/zynqberrydemo1.srcs/sources_1/bd/zsys/ipshared/b65a
    c:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/zynqberrydemo1.srcs/sources_1/bd/zsys/ipshared/0ab1/hdl
    c:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/zynqberrydemo1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl
  } {
      E:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      E:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      E:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_vhdl -lib xil_defaultlib {
      C:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/.Xil/Vivado-6676-DESKTOP-FGTB7AJ/realtime/zsys_axi_reg32_0_0_stub.vhdl
      C:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/.Xil/Vivado-6676-DESKTOP-FGTB7AJ/realtime/zsys_processing_system7_0_0_stub.vhdl
      C:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/.Xil/Vivado-6676-DESKTOP-FGTB7AJ/realtime/zsys_xlconcat_0_0_stub.vhdl
      C:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/.Xil/Vivado-6676-DESKTOP-FGTB7AJ/realtime/zsys_xlslice_0_0_stub.vhdl
      C:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/.Xil/Vivado-6676-DESKTOP-FGTB7AJ/realtime/zsys_xlslice_1_0_stub.vhdl
      C:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/.Xil/Vivado-6676-DESKTOP-FGTB7AJ/realtime/zsys_Video_IO_2_HDMI_TMDS_0_0_stub.vhdl
      C:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/.Xil/Vivado-6676-DESKTOP-FGTB7AJ/realtime/zsys_axi_vdma_0_1_stub.vhdl
      C:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/.Xil/Vivado-6676-DESKTOP-FGTB7AJ/realtime/zsys_axis_fb_conv_0_0_stub.vhdl
      C:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/.Xil/Vivado-6676-DESKTOP-FGTB7AJ/realtime/zsys_clk_wiz_1_0_stub.vhdl
      C:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/.Xil/Vivado-6676-DESKTOP-FGTB7AJ/realtime/zsys_v_axi4s_vid_out_0_0_stub.vhdl
      C:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/.Xil/Vivado-6676-DESKTOP-FGTB7AJ/realtime/zsys_v_tc_0_0_stub.vhdl
      C:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/.Xil/Vivado-6676-DESKTOP-FGTB7AJ/realtime/zsys_axi_vdma_0_0_stub.vhdl
      C:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/.Xil/Vivado-6676-DESKTOP-FGTB7AJ/realtime/zsys_axis_data_fifo_0_0_stub.vhdl
      C:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/.Xil/Vivado-6676-DESKTOP-FGTB7AJ/realtime/zsys_axis_data_fifo_3_0_stub.vhdl
      C:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/.Xil/Vivado-6676-DESKTOP-FGTB7AJ/realtime/zsys_axis_data_fifo_4_0_stub.vhdl
      C:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/.Xil/Vivado-6676-DESKTOP-FGTB7AJ/realtime/zsys_axis_raw_demosaic_0_0_stub.vhdl
      C:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/.Xil/Vivado-6676-DESKTOP-FGTB7AJ/realtime/zsys_axis_raw_unpack_0_0_stub.vhdl
      C:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/.Xil/Vivado-6676-DESKTOP-FGTB7AJ/realtime/zsys_csi2_d_phy_rx_0_0_stub.vhdl
      C:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/.Xil/Vivado-6676-DESKTOP-FGTB7AJ/realtime/zsys_csi_to_axis_0_0_stub.vhdl
      C:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/.Xil/Vivado-6676-DESKTOP-FGTB7AJ/realtime/zsys_proc_sys_reset_0_0_stub.vhdl
      C:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/.Xil/Vivado-6676-DESKTOP-FGTB7AJ/realtime/zsys_proc_sys_reset_1_0_stub.vhdl
      C:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/.Xil/Vivado-6676-DESKTOP-FGTB7AJ/realtime/zsys_rst_processing_system7_0_50M_0_stub.vhdl
      C:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/.Xil/Vivado-6676-DESKTOP-FGTB7AJ/realtime/zsys_xbar_0_stub.vhdl
      C:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/.Xil/Vivado-6676-DESKTOP-FGTB7AJ/realtime/zsys_axi_i2s_adi_0_0_stub.vhdl
      C:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/.Xil/Vivado-6676-DESKTOP-FGTB7AJ/realtime/zsys_axis_to_i2s_0_0_stub.vhdl
      C:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/.Xil/Vivado-6676-DESKTOP-FGTB7AJ/realtime/zsys_i2s_to_pwm_0_0_stub.vhdl
      C:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/.Xil/Vivado-6676-DESKTOP-FGTB7AJ/realtime/zsys_xadc_wiz_0_0_stub.vhdl
      C:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/.Xil/Vivado-6676-DESKTOP-FGTB7AJ/realtime/zsys_auto_pc_2_stub.vhdl
      C:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/.Xil/Vivado-6676-DESKTOP-FGTB7AJ/realtime/zsys_auto_pc_1_stub.vhdl
      C:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/.Xil/Vivado-6676-DESKTOP-FGTB7AJ/realtime/zsys_auto_pc_0_stub.vhdl
      C:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/zynqberrydemo1.srcs/sources_1/bd/zsys/synth/zsys.vhd
      C:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/zynqberrydemo1.srcs/sources_1/bd/zsys/hdl/zsys_wrapper.vhd
    }
      rt::read_vhdl -lib xpm E:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top zsys_wrapper
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "C:/Users/house/Downloads/te0726-zynqberrydemo1-vivado_2018.2-build_03_20181120163939/zynqberrydemo1/vivado/.Xil/Vivado-6676-DESKTOP-FGTB7AJ/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
